import os
from groq import AsyncGroq
from src.utils.settings import settings

# Find the absolute path to the ai-development-system folder (one level up from backend)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
AGENTS_DIR = os.path.join(BASE_DIR, "ai-development-system", "agents")

if settings.GROQ_API_KEY:
    client = AsyncGroq(api_key=settings.GROQ_API_KEY)
    MODEL_NAME = "llama-3.3-70b-versatile"
else:
    client = None
    MODEL_NAME = None


async def _query_llm_async(system_prompt: str, user_prompt: str) -> str:
    """Helper to query the Gemini model with system instructions."""
    if not client:
        # Simulation mode responses
        if "Research & Intelligence Agent" in system_prompt:
            return "Simulation Research: Verified standards. Architecture requires modular components."
        elif "Solution Architect" in system_prompt:
            return "Simulation Architecture: Configured database and API layout. Models prepared."
        else:
            return "Simulation Implementation:\n<html><body><h1>Deep Build Website</h1></body></html>"

    try:
        response = await client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.2
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        return f"Error: {e}"


def _load_agent_file(agent_name: str, file_name: str) -> str:
    """Reads a configuration or instruction markdown file for an agent."""
    path = os.path.join(AGENTS_DIR, agent_name, file_name)
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    return ""


async def run_deep_build_pipeline(user_prompt: str) -> str:
    """
    Runs the multi-agent pipeline asynchronously.
    Returns the final HTML code generated by the Implementation Engineer.
    """
    # ─── PHASE 1: RESEARCH ──────────────────────────────────────────────────────
    research_prompt = _load_agent_file("research-agent", "prompt.md")
    research_instructions = _load_agent_file("research-agent", "instructions.md")
    research_constraints = _load_agent_file("research-agent", "constraints.md")

    full_research_system = f"{research_prompt}\n\n{research_instructions}\n\n{research_constraints}"
    
    research_output = await _query_llm_async(
        system_prompt=full_research_system,
        user_prompt=f"Generate the full research package for this project: {user_prompt}. Provide sections matching research_package.md, competitors.md, database_analysis.md, etc."
    )

    # ─── PHASE 2: ARCHITECTURE ──────────────────────────────────────────────────
    architect_prompt = _load_agent_file("solution-architect", "prompt.md")
    architect_instructions = _load_agent_file("solution-architect", "instructions.md")
    architect_constraints = _load_agent_file("solution-architect", "constraints.md")

    full_architect_system = f"{architect_prompt}\n\n{architect_instructions}\n\n{architect_constraints}"
    
    architect_output = await _query_llm_async(
        system_prompt=full_architect_system,
        user_prompt=f"Read this research: {research_output[:5000]}. Design the architecture. Provide folder structures, models, API schemas, and milestones matching folder_structure.md, api_design.md, database_schema.md."
    )

    # ─── PHASE 3: IMPLEMENTATION ────────────────────────────────────────────────
    engineer_prompt = _load_agent_file("implementation-engineer", "prompt.md")
    engineer_instructions = _load_agent_file("implementation-engineer", "instructions.md")
    engineer_constraints = _load_agent_file("implementation-engineer", "constraints.md")

    full_engineer_system = f"{engineer_prompt}\n\n{engineer_instructions}\n\n{engineer_constraints}"
    
    engineer_output = await _query_llm_async(
        system_prompt=full_engineer_system,
        user_prompt=f"Based on Research: {research_output[:3000]} and Architecture: {architect_output[:3000]}.\nGenerate ONLY the full, working HTML code for the website (with embedded CSS/JS). No markdown explanations."
    )
    
    raw_output = engineer_output
    if raw_output.startswith("```html"):
        raw_output = raw_output[7:]
    if raw_output.startswith("```"):
        raw_output = raw_output[3:]
    if raw_output.endswith("```"):
        raw_output = raw_output[:-3]

    return raw_output.strip()
