from sqlalchemy import Column, Integer, String, Text, ForeignKey, DateTime
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from src.utils.db import Base


class ProjectModel(Base):
    """
    Stores each website project created by a user.
    One user can have many projects.
    """
    __tablename__ = "projects"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("user_table.id"), nullable=False)
    title = Column(String, nullable=False, default="Untitled Project")
    description = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationship: one project has many chat messages
    chat_messages = relationship(
        "ChatMessageModel",
        back_populates="project",
        cascade="all, delete-orphan"
    )


class ChatMessageModel(Base):
    """
    Stores individual chat messages inside a project.
    'role' is either 'user' (sent by user) or 'ai' (response from AI).
    'generated_code' stores the HTML/CSS/JS code the AI produced (if any).
    """
    __tablename__ = "chat_messages"

    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id"), nullable=False)
    role = Column(String, nullable=False)          # 'user' or 'ai'
    message_text = Column(Text, nullable=False)    # the chat text
    generated_code = Column(Text, nullable=True)   # HTML code generated by AI
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationship: each message belongs to one project
    project = relationship("ProjectModel", back_populates="chat_messages")
