"""initial_migration

Revision ID: da4c6fc78333
Revises: 
Create Date: 2026-06-29 17:13:10.689579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4c6fc78333'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('City', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('State', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Users_pkey')),
    sa.UniqueConstraint('Email', name=op.f('Users_Email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('Phone', name=op.f('Users_Phone_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
